pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "jhh0101/portfolio-front"
        DOCKER_TAG = "v${BUILD_NUMBER}"
        GIT_REPO_URL = "github.com/jhh0101/portfolio_front.git"

        GIT_EMAIL = "jenkins@bot.com"
        GIT_NAME = "Jenkins Bot"

        VITE_API_BASE_URL = "/api"
    }

    stages {
        stage('1. Git Checkout') {
            steps {
                git branch: 'main', url: "https://${GIT_REPO_URL}"
            }
        }

        stage('2. Build React (Vite)') {
            steps {
                script {
                    sh "npm install"

                    withCredentials([string(credentialsId: 'toss-client-secret', variable: 'TOSS_KEY')]) {
                        sh "VITE_API_BASE_URL=${VITE_API_BASE_URL} VITE_TOSS_CLIENT_KEY=${TOSS_KEY} npm run build"
                    }
                }
            }
        }

        stage('3. Docker Build & Push') {
                    steps {
                        script {
                            withCredentials([usernamePassword(credentialsId: 'docker-hub-login', passwordVariable: 'DOCKER_PW', usernameVariable: 'DOCKER_ID')]) {
                                sh "docker login -u ${DOCKER_ID} -p ${DOCKER_PW}"

                                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                                sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"

                                sh "docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest"
                                sh "docker push ${DOCKER_IMAGE}:latest"
                            }
                        }
                    }
                }

        stage('4. Update Manifest & Git Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-token', passwordVariable: 'GIT_PW', usernameVariable: 'GIT_USER')]) {
                    script {
                        sh "sed -i 's|image: ${DOCKER_IMAGE}:.*|image: ${DOCKER_IMAGE}:${DOCKER_TAG}|g' k8s/deployment.yml"

                        sh """
                            git config user.email "${GIT_EMAIL}"
                            git config user.name "${GIT_NAME}"
                            git add k8s/deployment.yml
                            git commit -m "Deploy: Update Frontend image to ${DOCKER_TAG} [skip ci]"
                            git push https://${GIT_USER}:${GIT_PW}@${GIT_REPO_URL} HEAD:main
                        """
                    }
                }
            }
        }

        stage('5. Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'k8s-config']) {
                    script {
                        sh "kubectl apply -f k8s/deployment.yml"
                        sh "kubectl apply -f k8s/service.yml"

                        sh "kubectl rollout restart deployment/frontend-deployment"
                        sh "kubectl rollout status deployment/frontend-deployment"
                    }
                }
            }
        }
    }
}